FROM php:7.2-fpm

WORKDIR /var/www
RUN mkdir /usr/src/php/ % mkdir /usr/src/php/ext/
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    zlib1g-dev \
    libicu-dev \
    g++\
    libxml2-dev

RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl gettext pdo

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www
RUN echo "root:secret" | chpasswd
USER www
EXPOSE 9000

CMD ["php-fpm"]